import { ArticleLayout, ArticleBody } from "../../lib/article";
const faqs = [
  { q: "Is Orijen worth the high price?", a: "If budget allows, yes. Orijen's 75-85% animal ingredient content is unmatched. You're paying for premium sourcing and high meat content. However, ACANA (same maker) offers 80% of the quality at a lower price." },
  { q: "Is Orijen good for kittens/puppies?", a: "Yes — Orijen offers specific puppy and kitten formulas. The high protein content supports growth. Introduce gradually and monitor stool quality as the rich food can cause loose stools initially." },
  { q: "Has Orijen been linked to DCM in dogs?", a: "Orijen was named in some FDA reports on grain-free diets and DCM (dilated cardiomyopathy), but no causal link has been established. The FDA investigation is ongoing. Consult your vet if concerned." },
];
export default function Page() {
  return (
    <ArticleLayout title="Orijen Pet Food Review — Ingredient Analysis | CanMyPetEat" description="Detailed ingredient analysis of Orijen pet food. Rating: A. Ultra-premium with 75-85% animal ingredients." canonical="/brand-review/orijen" petType="dog" food="Orijen (Brand)" safety="safe">
      <ArticleBody quickAnswer="Overall Rating: A — Orijen is one of the highest-quality commercial pet foods available. With 75-85% animal ingredients (including fresh, raw, and dehydrated), it closely mirrors the natural diet of dogs and cats. Made by Champion Petfoods in their own facilities with strict quality control." details="PROS: Extremely high animal ingredient content (75-85%). Uses fresh and raw animal ingredients, not just meals. WholePrey philosophy includes meat, organs, and cartilage for complete nutrition. No grains, corn, wheat, soy, or artificial preservatives. Multiple protein sources per formula (typically 5-8 animal ingredients). Made in Champion Petfoods' own kitchens (not outsourced). Transparent sourcing from known suppliers. CONS: One of the most expensive commercial pet foods. Very high protein content may not suit pets with kidney issues. Rich formulas can cause digestive upset during transition. Some formulas contain legumes (controversial ingredient). Limited availability in some regions. TYPICAL INGREDIENTS: Fresh free-run chicken, fresh whole eggs, fresh wild-caught flounder, fresh turkey, fresh chicken liver — real whole animal ingredients dominate." symptoms="" whatToDo="Transition slowly over 10-14 days when switching to Orijen. Start with 25% Orijen / 75% current food, increasing gradually. The high protein content can cause loose stools if switched too quickly. Feed less than lower-quality foods — Orijen is calorie-dense." safeAlternatives="Same quality tier: ACANA (A-, same maker, slightly less meat, more affordable). Similar quality: Stella & Chewy's, The Honest Kitchen, Farmina N&D." faqs={faqs} />
    </ArticleLayout>
  );
}
