import { ArticleLayout, ArticleBody } from "../../lib/article";
const faqs = [
  { q: "Is Royal Canin good for cats?", a: "Royal Canin's breed-specific and veterinary diets are well-formulated. However, their regular lines often list corn or wheat as the first ingredient, which isn't ideal for obligate carnivores. The prescription line is excellent." },
  { q: "Why is Royal Canin so expensive?", a: "You're paying for research, veterinary formulation, and breed-specific targeting. Whether it's worth the price depends on your pet's needs — the prescription diets justify the cost, but regular formulas have ingredients similar to cheaper brands." },
  { q: "Royal Canin vs Hill's?", a: "Both are vet-recommended brands with strong prescription lines. Hill's has more clinical research backing. Royal Canin has more breed-specific options. Ingredient quality is similar — both use some grains and fillers in regular lines." },
];
export default function Page() {
  return (
    <ArticleLayout title="Royal Canin Pet Food Review — Ingredient Analysis | CanMyPetEat" description="Detailed ingredient analysis of Royal Canin pet food. Rating: B. Major brand with strong veterinary diets but some filler concerns." canonical="/brand-review/royal-canin" petType="dog" food="Royal Canin (Brand)" safety="safe">
      <ArticleBody quickAnswer="Overall Rating: B — Royal Canin is a major pet food brand owned by Mars, Inc. They offer an impressive range of breed-specific and veterinary prescription diets. The prescription and breed-specific lines are well-formulated. However, their regular formulas often use corn, wheat, and by-products as primary ingredients, which brings down the overall rating." details="PROS: Extensive breed-specific formulas (unique in the industry). Excellent veterinary prescription diets for specific health conditions. Strong research and development program. Wide global availability. Good manufacturing standards. Multiple formulas for life stages, sizes, and specific needs. CONS: Owned by Mars, Inc. (mass-market food conglomerate). Corn and wheat are often the first ingredients in regular formulas. Uses chicken by-product meal in many products. Some products contain BHA preservative (controversial). Premium pricing for what are essentially mid-range ingredients. Regular formulas don't justify the price compared to similarly-priced premium brands. TYPICAL INGREDIENTS (Adult): Corn, chicken by-product meal, wheat gluten, corn gluten meal, chicken fat — corn appears before any meat ingredient in some formulas." symptoms="" whatToDo="Royal Canin prescription diets are excellent when recommended by your vet. Breed-specific formulas are a good choice if your breed has known dietary needs. For regular daily feeding of healthy pets, you can find better ingredient quality at similar or lower price points from brands like Blue Buffalo or ACANA." safeAlternatives="Similar quality: Hill's Science Diet (B+), Purina Pro Plan (B+). Higher quality: Blue Buffalo (A-), ACANA (A-), Orijen (A). Budget alternative with similar ingredients: IAMS (B)." faqs={faqs} />
    </ArticleLayout>
  );
}
