import { ArticleLayout, ArticleBody } from "../../lib/article";
const faqs = [
  { q: "Can cats with kidney problems eat spinach?", a: "No — cats with any kidney or urinary issues should avoid spinach completely. The oxalates can worsen kidney function and contribute to crystal/stone formation." },
  { q: "Can cats eat raw spinach?", a: "Small amounts of raw spinach are not toxic, but cooking reduces the oxalate content and makes it easier to digest. Steamed is better than raw." },
  { q: "Is spinach in cat food safe?", a: "Small amounts of spinach in commercial cat food are generally fine — the quantities are carefully controlled. The concern is mainly with feeding significant amounts of fresh spinach as a treat." },
];
export default function Page() {
  return (
    <ArticleLayout title="Can Cats Eat Spinach? With Caution — Kidney Risk | CanMyPetEat" description="Spinach is safe for healthy cats in small amounts but should be avoided by cats with kidney or urinary issues due to oxalates." canonical="/can-cats-eat/spinach" petType="cat" food="Spinach" safety="caution">
      <ArticleBody quickAnswer="With caution — spinach is not toxic to healthy cats in small amounts, but it contains calcium oxalates which can contribute to urinary crystals and kidney stones. Cats with any history of kidney disease, urinary tract issues, or FLUTD should avoid spinach entirely. For healthy cats, tiny amounts of cooked spinach are okay occasionally." details="Spinach is nutrient-dense for humans but presents specific risks for cats. The primary concern is calcium oxalate — spinach is high in oxalic acid, which binds with calcium to form calcium oxalate crystals. These crystals can accumulate in the urinary tract, leading to painful urinary blockages or kidney stones. Male cats are especially at risk for urinary blockages, which can be life-threatening. Cats with existing kidney disease, a history of urinary crystals, or feline lower urinary tract disease (FLUTD) should never eat spinach. For healthy cats, the occasional tiny amount of cooked spinach is unlikely to cause problems. Cooking does reduce oxalate content somewhat. Spinach also contains iron and some vitamins, but cats get everything they need from meat." symptoms="In susceptible cats: difficulty urinating, blood in urine, frequent urination attempts, crying while urinating, licking urinary area" whatToDo="For healthy cats only: lightly steam spinach (reduces oxalates), let cool, and offer a tiny portion (1-2 small leaves worth). No butter, oil, garlic, or seasonings. If your cat has any urinary or kidney history, avoid spinach completely." safeAlternatives="Safer green vegetables for cats: cooked green beans, steamed broccoli (small amounts), cucumber, and zucchini — all lower in oxalates than spinach." faqs={faqs} />
    </ArticleLayout>
  );
}
