const SITE_URL = "https://canmypeteat.app";
const pages = [
  { url: "/", priority: "1.0", changefreq: "weekly" },
  { url: "/can-dogs-eat/almonds", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/apples", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/asparagus", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/avocado", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/bacon", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/bamboo-shoot", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/bananas", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/beef", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/beet", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/beets", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/bell-pepper", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/bison", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/blackberries", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/blackberry", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/blueberries", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/bread", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/broccoli", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/cabbage", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/cantaloupe", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/carrots", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/cauliflower", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/celery", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/cheese", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/cherries", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/chicken-bones", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/chocolate", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/cinnamon", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/coconut-oil", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/coconut", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/corn", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/cottage-cheese", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/cranberries", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/cucumber", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/dates", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/dragon-fruit", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/duck", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/durian", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/edamame", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/eggs", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/garlic", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/ginger", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/grapes", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/green-beans", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/guava", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/ham", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/honey", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/hot-dog", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/ice-cream", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/kiwi", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/lamb", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/lettuce", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/longan", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/lychee", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/mango", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/mushrooms", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/noodles", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/oatmeal", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/onions", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/oranges", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/papaya", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/passion-fruit", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/peach", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/peanut-butter", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/pear", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/pineapple", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/pizza", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/plum", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/popcorn", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/pork", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/potato", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/pumpkin", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/raspberry", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/rice", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/salmon", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/sardines", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/sausage", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/shrimp", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/spinach", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/squash", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/strawberries", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/sweet-corn", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/sweet-potato", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/taro", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/tofu", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/tomato", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/tuna", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/turkey", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/venison", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/watermelon", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/wax-apple", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/wheatgrass", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/whipped-cream", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/xylitol", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/yogurt", priority: "0.8", changefreq: "monthly" },
  { url: "/can-dogs-eat/zucchini", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/apple", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/asparagus", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/avocado", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/bacon", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/banana", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/beef", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/blueberry", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/bread", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/broccoli", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/cantaloupe", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/carrot-cooked", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/carrot", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/celery", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/cheese", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/chicken", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/chocolate", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/coconut", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/corn", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/cranberry", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/cucumber", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/dragon-fruit", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/dragonfruit", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/duck", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/eggs", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/garlic", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/grape", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/green-bean", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/guava", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/ham", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/ice-cream", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/kiwi", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/lamb", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/lettuce", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/liver", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/longan", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/lychee", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/mango-dried", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/mango-full", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/mango", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/melon", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/milk", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/oatmeal", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/onions", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/papaya", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/passion-fruit", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/pea", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/peach", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/peanut-butter", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/pineapple", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/pork", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/potato", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/pumpkin", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/rice", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/salmon", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/sardine", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/shrimp", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/spinach", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/squash", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/steak", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/strawberry", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/sweet-potato", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/taro", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/tuna-canned", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/tuna-cooked", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/tuna-raw", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/tuna", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/turkey", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/watermelon", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/wax-apple", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/yogurt", priority: "0.8", changefreq: "monthly" },
  { url: "/can-cats-eat/zucchini", priority: "0.8", changefreq: "monthly" },
  { url: "/brand-review/acana", priority: "0.8", changefreq: "monthly" },
  { url: "/brand-review/blue-buffalo", priority: "0.8", changefreq: "monthly" },
  { url: "/brand-review/fancy-feast", priority: "0.8", changefreq: "monthly" },
  { url: "/brand-review/friskies", priority: "0.8", changefreq: "monthly" },
  { url: "/brand-review/hills-science-diet", priority: "0.8", changefreq: "monthly" },
  { url: "/brand-review/iams", priority: "0.8", changefreq: "monthly" },
  { url: "/brand-review/meow-mix", priority: "0.8", changefreq: "monthly" },
  { url: "/brand-review/merrick", priority: "0.8", changefreq: "monthly" },
  { url: "/brand-review/orijen", priority: "0.8", changefreq: "monthly" },
  { url: "/brand-review/purina", priority: "0.8", changefreq: "monthly" },
  { url: "/brand-review/royal-canin", priority: "0.8", changefreq: "monthly" },
  { url: "/brand-review/sheba", priority: "0.8", changefreq: "monthly" },
  { url: "/brand-review/taste-of-the-wild", priority: "0.8", changefreq: "monthly" },
  { url: "/brand-review/whiskas", priority: "0.8", changefreq: "monthly" },
  { url: "/pet-safety/cat-ate-chocolate", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/cat-ate-lily", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/cat-ate-onion", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/cat-safe-plants", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/dog-ate-chocolate", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/dog-ate-grapes", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/dog-ate-onion", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/dog-ate-xylitol", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/foods-toxic-to-cats", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/foods-toxic-to-dogs", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/holiday-food-dangers", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/human-foods-safe-for-cats", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/human-foods-safe-for-dogs", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/pet-emergency-contacts", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/pet-proof-kitchen", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/puppy-safe-foods", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/safe-fruits-for-cats", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/safe-fruits-for-dogs", priority: "0.9", changefreq: "monthly" },
  { url: "/pet-safety/senior-dog-diet", priority: "0.9", changefreq: "monthly" },
];

function SitemapXml() { return null; }

export async function getServerSideProps({ res }) {
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages.map(p => `  <url>
    <loc>${SITE_URL}${p.url}</loc>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>
  </url>`).join("\n")}
</urlset>`;

  res.setHeader("Content-Type", "text/xml");
  res.write(sitemap);
  res.end();
  return { props: {} };
}

export default SitemapXml;
